<?php
// install/index.php - First-time installer wizard for PRD
declare(strict_types=1);

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$root = dirname(__DIR__); // this project folder only
$configLocal = $root . '/config.local.php';
$lockFile = $root . '/db/INSTALL_LOCK';
$loaderDb = $root . '/db/db.php';
$functionsPath = $root . '/includes/functions.php';

// Include functions early so we have access to language helper functions like __('...') and set_language()
if (is_file($functionsPath)) {
    require_once $functionsPath;
}

// Handle language selection submission right away if posted
$serverMethod = isset($_SERVER['REQUEST_METHOD']) && is_string($_SERVER['REQUEST_METHOD']) ? $_SERVER['REQUEST_METHOD'] : 'GET';
if ($serverMethod === 'POST' && isset($_POST['selected_lang']) && is_string($_POST['selected_lang'])) {
    $chosenLang = preg_replace('/[^a-zA-Z_]/', '', $_POST['selected_lang']);
    if (is_string($chosenLang) && $chosenLang !== '') {
        if (function_exists('set_language')) {
            set_language($chosenLang);
        } else {
            $_SESSION['lang'] = $chosenLang;
        }
    }
}

$step = isset($_POST['step']) ? (int)$_POST['step'] : 1;
$error = '';
$message = '';

function install_db_is_empty(PDO $pdo): bool {
    $stmt = $pdo->query('SHOW TABLES');
    $tables = $stmt !== false ? $stmt->fetchAll(PDO::FETCH_COLUMN) : [];
    return is_array($tables) && count($tables) === 0;
}

function install_import_sql(PDO $pdo, string $path): void {
    if (!is_file($path)) {
        throw new RuntimeException("Missing SQL file: {$path}");
    }
    $sql = file_get_contents($path);
    if ($sql === false) {
        throw new RuntimeException("Could not read SQL file: {$path}");
    }
    $sql = preg_replace('/\/\*![0-9]{5}.*?\*\//s', '', $sql);
    $sql = preg_replace('/^--.*$/m', '', $sql);
    $sql = preg_replace('/^\/\*M!.*$/m', '', $sql);
    $statements = is_string($sql) ? array_filter(array_map('trim', explode(';', $sql))) : [];

    $pdo->exec('SET FOREIGN_KEY_CHECKS=0');
    try {
        foreach ($statements as $statement) {
            if ($statement === '') {
                continue;
            }
            if (preg_match('/^(SET|USE)\s+/i', $statement)) {
                continue;
            }
            $pdo->exec($statement);
        }
    } finally {
        $pdo->exec('SET FOREIGN_KEY_CHECKS=1');
    }
}

function install_latest_schema_version(string $migrationsDir): int {
    $latest = 0;
    if (is_dir($migrationsDir)) {
        $globFiles = glob($migrationsDir . '/*.php');
        if ($globFiles !== false) {
            foreach ($globFiles as $file) {
                $m = [];
                if (preg_match('/(\d+)_/', basename($file), $m)) {
                    $latest = max($latest, (int)$m[1]);
                }
            }
        }
    }
    return max(1, $latest);
}

function install_write_config_local(string $path, string $host, string $db, string $user, string $pass): void {
    $hostE = var_export($host, true);
    $dbE   = var_export($db, true);
    $userE = var_export($user, true);
    $passE = var_export($pass, true);

    $content = <<<PHP
<?php
declare(strict_types=1);
// config.local.php - Generated by installer. Do not commit. This project folder only.
if (!defined('BASE_PATH')) {
    \$docRoot = isset(\$_SERVER['DOCUMENT_ROOT']) && is_string(\$_SERVER['DOCUMENT_ROOT']) ? rtrim(str_replace('\\\\', '/', \$_SERVER['DOCUMENT_ROOT']), '/') : '';
    \$projectRoot = rtrim(str_replace('\\\\', '/', dirname(__FILE__)), '/');
    \$basePath = \$docRoot !== '' ? str_replace(\$docRoot, '', \$projectRoot) : '';
    define('BASE_PATH', \$basePath);
}

\$host = {$hostE};
\$db = {$dbE};
\$user = {$userE};
\$pass = {$passE};
\$charset = 'utf8mb4';

\$dsn = "mysql:host=\$host;dbname=\$db;charset=\$charset";
\$options = [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES => false,
];

\$logDir = __DIR__ . '/logs';
if (!is_dir(\$logDir)) {
    @mkdir(\$logDir, 0755, true);
}

try {
    \$pdo = new PDO(\$dsn, \$user, \$pass, \$options);

    // Force MySQL session time zone to UTC (+00:00) to prevent the 1-hour drift
    \$pdo->exec("SET time_zone = '+00:00';");

    if (is_file(__DIR__ . '/db/maintenance_guard.php')) {
        require_once __DIR__ . '/db/maintenance_guard.php';
        if (function_exists('check_maintenance_mode')) {
            check_maintenance_mode(\$pdo);
        }
    }
} catch (PDOException \$e) {
    throw new PDOException('Database Connection Failed: ' . \$e->getMessage(), (int)\$e->getCode());
}
PHP;

    $result = @file_put_contents($path, $content);
    if ($result === false) {
        $last = error_get_last();
        $detail = isset($last['message']) && is_string($last['message']) ? $last['message'] : 'unknown error';
        throw new RuntimeException(
            'Could not write config.local.php (' . $path . '). PHP said: ' . $detail
        );
    }
}

function install_write_loader_db_php(string $path): void {
    $content = <<<'PHP'
<?php
declare(strict_types=1);
// db/db.php - Generated by installer (loader only). Secrets live in config.local.php.
$projectRoot = dirname(__DIR__);
$configLocal = $projectRoot . '/config.local.php';

if (is_file($configLocal)) {
    require $configLocal;
    return;
}

$script = isset($_SERVER['SCRIPT_NAME']) && is_string($_SERVER['SCRIPT_NAME']) ? str_replace('\\', '/', $_SERVER['SCRIPT_NAME']) : '';
if (strpos($script, '/install/') !== false || str_ends_with($script, '/install')) {
    return;
}

$base = str_replace('\\', '/', dirname($script));
if (preg_match('#/(user|admin|api|actions|db|partials|includes)(/|$)#', $base)) {
    $base = dirname($base);
}
$base = rtrim($base, '/');
header('Location: ' . $base . '/install/');
exit;
PHP;

    $dir = dirname($path);
    if (!is_dir($dir)) {
        if (!@mkdir($dir, 0755, true) && !is_dir($dir)) {
            throw new RuntimeException('Could not create db/ directory.');
        }
    }
    if (@file_put_contents($path, $content) === false) {
        $last = error_get_last();
        $msg = isset($last['message']) && is_string($last['message']) ? $last['message'] : 'unknown';
        throw new RuntimeException('Could not write db/db.php loader. PHP said: ' . $msg);
    }
}

function install_bootstrap_permissions(PDO $pdo): void {
    $registryPath = dirname(__DIR__) . '/db/permissions_registry.php';
    if (!is_file($registryPath)) {
        throw new RuntimeException("Missing permissions registry: {$registryPath}");
    }
    
    /** @var array{permissions?: array<string, string>, default_roles?: array<string, array<int, string>>} $registry */
    $registry = include $registryPath;
    $permissions = isset($registry['permissions']) && is_array($registry['permissions']) ? $registry['permissions'] : [];
    $defaultRoles = isset($registry['default_roles']) && is_array($registry['default_roles']) ? $registry['default_roles'] : [];

    $insPerm = $pdo->prepare(
        'INSERT IGNORE INTO permissions (permission_key, description) VALUES (?, ?)'
    );
    foreach ($permissions as $key => $desc) {
        $insPerm->execute([$key, $desc]);
    }

    foreach ($defaultRoles as $roleName => $permKeys) {
        $stmt = $pdo->prepare("SELECT id FROM roles WHERE role_name = ?");
        $stmt->execute([$roleName]);
        $roleId = $stmt->fetchColumn();

        if ($roleId) {
            foreach ($permKeys as $key) {
                $pStmt = $pdo->prepare("SELECT id FROM permissions WHERE permission_key = ?");
                $pStmt->execute([$key]);
                $permId = $pStmt->fetchColumn();

                if ($permId) {
                    $mapStmt = $pdo->prepare("INSERT IGNORE INTO role_permissions (role_id, permission_id) VALUES (?, ?)");
                    $mapStmt->execute([$roleId, $permId]);
                }
            }
        }
    }
}

function install_show_complete_page(): void {
    $completeTitle = function_exists('__') ? __('install.complete_title') : 'Installation Complete';
    $completeHeading = function_exists('__') ? __('install.complete_heading') : 'All Done, Thank You!';
    $completeDesc = function_exists('__') ? __('install.complete_desc') : 'Your application has been successfully installed and configured.';
    $loginLink = function_exists('__') ? __('install.login_link') : 'Log in to your account';
    $homeLink = function_exists('__') ? __('install.home_link') : 'Visit homepage';
    $deleteHint = function_exists('__') ? __('install.delete_folder_hint') : 'Please remember to delete the install folder for security.';

    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= htmlspecialchars($completeTitle, ENT_QUOTES, 'UTF-8') ?></title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body class="bg-light d-flex align-items-center justify-content-center min-vh-100">
        <div class="container" style="max-width: 600px;">
            <div class="card border-0 shadow-sm p-5 text-center bg-white">
                <h1 class="h4 fw-bold text-success mb-3"><?= htmlspecialchars($completeHeading, ENT_QUOTES, 'UTF-8') ?></h1>
                <p class="text-secondary small mb-4"><?= htmlspecialchars($completeDesc, ENT_QUOTES, 'UTF-8') ?></p>
                <div class="mb-4">
                    <a href="../user/login.php" class="btn btn-primary btn-sm px-3 fw-bold text-decoration-none me-2"><?= htmlspecialchars($loginLink, ENT_QUOTES, 'UTF-8') ?></a>
                    <a href="../index.php" class="btn btn-outline-secondary btn-sm px-3 text-decoration-none"><?= htmlspecialchars($homeLink, ENT_QUOTES, 'UTF-8') ?></a>
                </div>
                <p class="small text-muted mb-0"><em><?= htmlspecialchars($deleteHint, ENT_QUOTES, 'UTF-8') ?></em></p>
            </div>
        </div>
    </body>
    </html>
    <?php
    exit;
}

function install_load_pdo_from_config(string $configLocal): PDO {
    if (!is_file($configLocal)) {
        throw new RuntimeException('No config.local.php found.');
    }
    require $configLocal;
    if (!isset($pdo) || !($pdo instanceof PDO)) {
        throw new RuntimeException('Database connection not available.');
    }
    return $pdo;
}

// Probe write access inside this project folder only
$probeOk = false;
$probeError = '';
$probeFile = $root . '/.install_write_probe';
if (@file_put_contents($probeFile, 'ok') !== false) {
    $probeOk = true;
    @unlink($probeFile);
} else {
    $last = error_get_last();
    $probeError = isset($last['message']) && is_string($last['message']) ? $last['message'] : 'write failed';
}

// ---------- Lock / resume ----------
if (is_file($lockFile)) {
    install_show_complete_page();
}

if (is_file($configLocal) && $serverMethod !== 'POST') {
    try {
        $pdo = install_load_pdo_from_config($configLocal);
        $userCount = (int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn();
        if ($userCount > 0) {
            if (!is_dir($root . '/db')) {
                @mkdir($root . '/db', 0755, true);
            }
            if (!is_file($loaderDb)) {
                install_write_loader_db_php($loaderDb);
            }
            install_bootstrap_permissions($pdo);
            file_put_contents($lockFile, 'Installed ' . gmdate('c') . " (lock backfilled)\n");
            install_show_complete_page();
        }
        $_SESSION['install_db_ok'] = true;
        $step = 5; // Step 5 now represents the admin user creation step
        $message = __('install.msg_db_ready');
    } catch (\Throwable $e) {
        $error = __('install.err_config_load') . ' ' . $e->getMessage();
    }
}

// ---------- POST ----------
if ($serverMethod === 'POST') {
    try {
        if ($step === 1) {
            // Language selection completed, move to requirements check (Step 2)
            $step = 2;
        } elseif ($step === 2) {
            // Requirements passed, move to database configuration (Step 3)
            $step = 3;
        } elseif ($step === 3) {
            if (!$probeOk) {
                throw new RuntimeException(
                    __('install.err_write_permission') . ' ' . ($probeError !== '' ? __('install.detail_prefix') . ' ' . $probeError : '')
                );
            }

            $host = trim(isset($_POST['db_host']) && is_string($_POST['db_host']) ? $_POST['db_host'] : '127.0.0.1');
            $name = trim(isset($_POST['db_name']) && is_string($_POST['db_name']) ? $_POST['db_name'] : '');
            $user = trim(isset($_POST['db_user']) && is_string($_POST['db_user']) ? $_POST['db_user'] : '');
            $pass = isset($_POST['db_pass']) && is_string($_POST['db_pass']) ? $_POST['db_pass'] : '';

            if ($name === '' || $user === '') {
                throw new RuntimeException(__('install.err_db_required'));
            }

            $dsn = "mysql:host={$host};dbname={$name};charset=utf8mb4";
            $pdo = new PDO($dsn, $user, $pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);

            // Force MySQL session time zone to UTC (+00:00) during installation checks
            $pdo->exec("SET time_zone = '+00:00';");

            if (!install_db_is_empty($pdo)) {
                throw new RuntimeException(__('install.err_db_not_empty'));
            }

            install_write_config_local($configLocal, $host, $name, $user, $pass);
            install_write_loader_db_php($loaderDb);

            install_import_sql($pdo, $root . '/db/schema_baseline.sql');
            install_import_sql($pdo, $root . '/db/seed_baseline.sql');
            if (is_file($root . '/db/seed_permissions.sql')) {
                install_import_sql($pdo, $root . '/db/seed_permissions.sql');
            }
            if (is_file($root . '/db/seed_role_permissions.sql')) {
                install_import_sql($pdo, $root . '/db/seed_role_permissions.sql');
            }

            if (is_file($functionsPath)) {
                require_once $functionsPath;
            }
            $latest = install_latest_schema_version($root . '/db/migrations');
            if (function_exists('set_schema_version')) {
                set_schema_version($pdo, $latest);
            } else {
                $stmt = $pdo->prepare(
                    "INSERT INTO site_settings (setting_key, setting_value) VALUES ('schema_version', ?)
                     ON DUPLICATE KEY UPDATE setting_value = ?"
                );
                $stmt->execute([(string)$latest, (string)$latest]);
            }

            $_SESSION['install_db_ok'] = true;
            $step = 5; // Move to admin creation
            $message = __('install.msg_schema_imported');
        } elseif ($step === 5) {
            $sessionDbOk = isset($_SESSION['install_db_ok']) && $_SESSION['install_db_ok'] === true;
            if (!$sessionDbOk || !is_file($configLocal)) {
                throw new RuntimeException(__('install.err_complete_db_first'));
            }

            $pdo = install_load_pdo_from_config($configLocal);

            $username = trim(isset($_POST['admin_username']) && is_string($_POST['admin_username']) ? $_POST['admin_username'] : '');
            $email    = trim(isset($_POST['admin_email']) && is_string($_POST['admin_email']) ? $_POST['admin_email'] : '');
            $password = isset($_POST['admin_password']) && is_string($_POST['admin_password']) ? $_POST['admin_password'] : '';
            $confirm  = isset($_POST['admin_password_confirm']) && is_string($_POST['admin_password_confirm']) ? $_POST['admin_password_confirm'] : '';

            if ($username === '' || $email === '' || $password === '') {
                throw new RuntimeException(__('install.err_admin_required'));
            }
            if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
                throw new RuntimeException(__('install.err_invalid_email'));
            }
            if (strlen($password) < 8) {
                throw new RuntimeException(__('install.err_password_length'));
            }
            if ($password !== $confirm) {
                throw new RuntimeException(__('install.err_passwords_match'));
            }

            $hash = password_hash($password, PASSWORD_DEFAULT);
            $roleId = 1;

            try {
                $stmt = $pdo->prepare("
                    INSERT INTO users (username, email, password_hash, role_id, email_verified, is_active, is_new_user)
                    VALUES (?, ?, ?, ?, 1, 1, 1)
                ");
                $stmt->execute([$username, $email, $hash, $roleId]);
            } catch (PDOException $e) {
                $stmt = $pdo->prepare("
                    INSERT INTO users (username, email, password_hash, role_id)
                    VALUES (?, ?, ?, ?)
                ");
                $stmt->execute([$username, $email, $hash, $roleId]);
            }

            $check = $pdo->prepare('SELECT COUNT(*) FROM users WHERE username = ?');
            $check->execute([$username]);
            if ((int)$check->fetchColumn() < 1) {
                throw new RuntimeException(__('install.err_admin_save_failed'));
            }

            install_bootstrap_permissions($pdo);

            if (!is_file($loaderDb)) {
                install_write_loader_db_php($loaderDb);
            }

            if (!is_dir($root . '/db')) {
                @mkdir($root . '/db', 0755, true);
            }
            file_put_contents($lockFile, 'Installed ' . gmdate('c') . "\n");
            unset($_SESSION['install_db_ok']);
            $step = 6; // Final success view
            $message = __('install.msg_installation_complete');
        }
    } catch (\Throwable $e) {
        $error = $e->getMessage();
        if ($step === 3 && is_file($configLocal) && empty($_SESSION['install_db_ok'])) {
            @unlink($configLocal);
        }
        if ($step === 5) {
            $step = 5;
            $_SESSION['install_db_ok'] = true;
        }
    }
}

$phpOk = version_compare(PHP_VERSION, '8.0.0', '>=');
$pdoOk = extension_loaded('pdo_mysql');
$logsDir = $root . '/logs';
$logsOk = is_dir($logsDir) ? is_writable($logsDir) : is_writable($root);
$reqsOk = $phpOk && $pdoOk && $logsOk && $probeOk;

$showDbForm = ($step === 4) || ($step === 3);

// Get available languages dynamically from the lang directory
$availableLanguages = [];
$langDir = $root . '/lang';
if (is_dir($langDir)) {
    $globLang = glob($langDir . '/*.php');
    if ($globLang !== false) {
        foreach ($globLang as $langFile) {
            $code = basename($langFile, '.php');
            $availableLanguages[$code] = ucwords(str_replace(['_', '-'], ' ', $code));
        }
    }
}
if (empty($availableLanguages)) {
    $availableLanguages = ['en' => 'English'];
}
asort($availableLanguages);

$currentActiveLang = function_exists('get_active_language') ? get_active_language() : 'en';
?>
<!DOCTYPE html>
<html lang="<?= htmlspecialchars($currentActiveLang, ENT_QUOTES, 'UTF-8') ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= htmlspecialchars(__('install.page_title') ?: 'Welcome to the Installer', ENT_QUOTES, 'UTF-8') ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light d-flex align-items-center justify-content-center min-vh-100 py-5">
    <div class="container" style="max-width: 600px;">
        <div class="card border-0 shadow-sm p-4 bg-white">
            <h1 class="h4 fw-bold text-dark mb-1"><?= htmlspecialchars(__('install.heading') ?: 'Welcome Please!', ENT_QUOTES, 'UTF-8') ?></h1>
            <p class="text-muted small mb-4"><?= htmlspecialchars(__('install.subheading') ?: 'We are delighted to help you set everything up safely. Thank you for choosing our software!', ENT_QUOTES, 'UTF-8') ?></p>

            <?php if ($error !== ''): ?>
                <div class="alert alert-danger alert-dismissible fade show shadow-sm small" role="alert">
                    <strong><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            <?php endif; ?>

            <?php if ($message !== '' && $step !== 6): ?>
                <div class="alert alert-success alert-dismissible fade show shadow-sm small" role="alert">
                    <strong><?= htmlspecialchars($message, ENT_QUOTES, 'UTF-8') ?></strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            <?php endif; ?>

            <?php if ($step === 6): ?>
                <h2 class="h5 fw-bold text-success mb-2"><?= htmlspecialchars(__('install.done_heading') ?: 'All Set Up, Thank You!', ENT_QUOTES, 'UTF-8') ?></h2>
                <p class="text-secondary small mb-3"><?= htmlspecialchars(__('install.done_message') ?: 'Your database and admin profile have been configured successfully.', ENT_QUOTES, 'UTF-8') ?></p>
                <p class="small mb-0">
                    <a href="../user/login.php" class="text-decoration-none fw-bold"><?= htmlspecialchars(__('install.login_link') ?: 'Please log in here', ENT_QUOTES, 'UTF-8') ?></a> · 
                    <a href="../index.php" class="text-decoration-none text-muted"><?= htmlspecialchars(__('install.home_link') ?: 'Visit home page', ENT_QUOTES, 'UTF-8') ?></a>
                </p>

            <?php elseif ($step === 5): ?>
                <h2 class="h5 fw-bold text-dark mb-1"><?= htmlspecialchars(__('install.admin_heading') ?: 'Create Administrator Account', ENT_QUOTES, 'UTF-8') ?></h2>
                <p class="text-muted small mb-3"><?= htmlspecialchars(__('install.admin_subheading') ?: 'Please provide details for your main administrator account below.', ENT_QUOTES, 'UTF-8') ?></p>
                
                <form method="post">
                    <input type="hidden" name="step" value="5">
                    
                    <div class="mb-3">
                        <label for="admin_username" class="form-label small fw-bold"><?= htmlspecialchars(__('install.admin_username_label') ?: 'Admin Username:', ENT_QUOTES, 'UTF-8') ?></label>
                        <input id="admin_username" name="admin_username" required autocomplete="username" class="form-control form-control-sm">
                    </div>
                    
                    <div class="mb-3">
                        <label for="admin_email" class="form-label small fw-bold"><?= htmlspecialchars(__('install.admin_email_label') ?: 'Admin Email Address:', ENT_QUOTES, 'UTF-8') ?></label>
                        <input id="admin_email" name="admin_email" type="email" required autocomplete="email" class="form-control form-control-sm">
                    </div>
                    
                    <div class="mb-3">
                        <label for="admin_password" class="form-label small fw-bold"><?= htmlspecialchars(__('install.admin_password_label') ?: 'Password (at least 8 characters please):', ENT_QUOTES, 'UTF-8') ?></label>
                        <input id="admin_password" name="admin_password" type="password" required autocomplete="new-password" class="form-control form-control-sm">
                    </div>
                    
                    <div class="mb-4">
                        <label for="admin_password_confirm" class="form-label small fw-bold"><?= htmlspecialchars(__('install.admin_confirm_password_label') ?: 'Confirm Password please:', ENT_QUOTES, 'UTF-8') ?></label>
                        <input id="admin_password_confirm" name="admin_password_confirm" type="password" required autocomplete="new-password" class="form-control form-control-sm">
                    </div>
                    
                    <button type="submit" class="btn btn-primary btn-sm px-4 fw-bold"><?= htmlspecialchars(__('install.finish_btn') ?: 'Save and Complete Installation, Please', ENT_QUOTES, 'UTF-8') ?></button>
                </form>

            <?php elseif ($step === 3 || $showDbForm): ?>
                <h2 class="h5 fw-bold text-dark mb-1"><?= htmlspecialchars(__('install.db_heading') ?: 'Database Connection Setup', ENT_QUOTES, 'UTF-8') ?></h2>
                <p class="text-muted small mb-3"><?= htmlspecialchars(__('install.db_hint') ?: 'Please enter your MySQL database connection credentials below.', ENT_QUOTES, 'UTF-8') ?></p>
                
                <form method="post">
                    <input type="hidden" name="step" value="3">
                    
                    <div class="mb-3">
                        <label for="db_host" class="form-label small fw-bold"><?= htmlspecialchars(__('install.db_host_label') ?: 'Database Host:', ENT_QUOTES, 'UTF-8') ?></label>
                        <input id="db_host" name="db_host" value="127.0.0.1" required class="form-control form-control-sm">
                    </div>
                    
                    <div class="mb-3">
                        <label for="db_name" class="form-label small fw-bold"><?= htmlspecialchars(__('install.db_name_label') ?: 'Database Name:', ENT_QUOTES, 'UTF-8') ?></label>
                        <input id="db_name" name="db_name" required class="form-control form-control-sm">
                    </div>
                    
                    <div class="mb-3">
                        <label for="db_user" class="form-label small fw-bold"><?= htmlspecialchars(__('install.db_user_label') ?: 'Database Username:', ENT_QUOTES, 'UTF-8') ?></label>
                        <input id="db_user" name="db_user" required autocomplete="off" class="form-control form-control-sm">
                    </div>
                    
                    <div class="mb-4">
                        <label for="db_pass" class="form-label small fw-bold"><?= htmlspecialchars(__('install.db_pass_label') ?: 'Database Password:', ENT_QUOTES, 'UTF-8') ?></label>
                        <input id="db_pass" name="db_pass" type="password" autocomplete="new-password" class="form-control form-control-sm">
                    </div>
                    
                    <button type="submit" class="btn btn-primary btn-sm px-4 fw-bold"><?= htmlspecialchars(__('install.db_submit_btn') ?: 'Test Connection and Proceed, Please', ENT_QUOTES, 'UTF-8') ?></button>
                </form>

            <?php elseif ($step === 2): ?>
                <h2 class="h5 fw-bold text-dark mb-3"><?= htmlspecialchars(__('install.req_heading') ?: 'System Requirements Check', ENT_QUOTES, 'UTF-8') ?></h2>
                
                <ul class="list-group list-group-flush mb-4 small">
                    <li class="list-group-item d-flex justify-content-between align-items-center <?= $phpOk ? 'text-success' : 'text-danger' ?>">
                        <span><?= htmlspecialchars(sprintf(__('install.req_php') ?: 'PHP Version >= 8.0.0 (Yours is: %s)', PHP_VERSION), ENT_QUOTES, 'UTF-8') ?></span>
                        <span><?= $phpOk ? '✓' : '✗' ?></span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center <?= $pdoOk ? 'text-success' : 'text-danger' ?>">
                        <span><?= htmlspecialchars(__('install.req_pdo') ?: 'PDO MySQL Extension Enabled', ENT_QUOTES, 'UTF-8') ?></span>
                        <span><?= $pdoOk ? '✓' : '✗' ?></span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center <?= $logsOk ? 'text-success' : 'text-danger' ?>">
                        <span><?= htmlspecialchars(__('install.req_logs') ?: 'Logs Directory Writable', ENT_QUOTES, 'UTF-8') ?></span>
                        <span><?= $logsOk ? '✓' : '✗' ?></span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center <?= $probeOk ? 'text-success' : 'text-danger' ?>">
                        <div>
                            <span><?= htmlspecialchars(__('install.req_probe') ?: 'Project Folder Write Permissions Checked', ENT_QUOTES, 'UTF-8') ?></span>
                            <?php if (!$probeOk && $probeError !== ''): ?>
                                <div class="text-muted small"><?= htmlspecialchars($probeError, ENT_QUOTES, 'UTF-8') ?></div>
                            <?php endif; ?>
                        </div>
                        <span><?= $probeOk ? '✓' : '✗' ?></span>
                    </li>
                </ul>

                <?php if ($reqsOk): ?>
                    <form method="post">
                        <input type="hidden" name="step" value="2">
                        <button type="submit" class="btn btn-primary btn-sm px-4 fw-bold"><?= htmlspecialchars(__('install.continue_btn') ?: 'Everything looks great, please continue', ENT_QUOTES, 'UTF-8') ?></button>
                    </form>
                <?php else: ?>
                    <div class="alert alert-warning small mb-0">
                        <?= htmlspecialchars(__('install.req_fail_msg') ?: 'Please fix the requirements highlighted above before proceeding. Thank you!', ENT_QUOTES, 'UTF-8') ?>
                    </div>
                <?php endif; ?>

            <?php else: ?>
                <!-- Step 1: Language Selection -->
                <h2 class="h5 fw-bold text-dark mb-1"><?= htmlspecialchars(__('install.lang_heading') ?: 'Choose Your Preferred Language', ENT_QUOTES, 'UTF-8') ?></h2>
                <p class="text-muted small mb-3"><?= htmlspecialchars(__('install.lang_hint') ?: 'Please select your preferred language for the installation process and application setup.', ENT_QUOTES, 'UTF-8') ?></p>
                
                <form method="post">
                    <input type="hidden" name="step" value="1">
                    
                    <div class="mb-4">
                        <label for="selected_lang" class="form-label small fw-bold"><?= htmlspecialchars(__('install.lang_label') ?: 'Language Choice:', ENT_QUOTES, 'UTF-8') ?></label>
                        <select id="selected_lang" name="selected_lang" class="form-select form-select-sm">
                            <?php foreach ($availableLanguages as $code => $label): ?>
                                <option value="<?= htmlspecialchars($code, ENT_QUOTES, 'UTF-8') ?>" <?= ($code === $currentActiveLang) ? 'selected' : '' ?>>
                                    <?= htmlspecialchars($label, ENT_QUOTES, 'UTF-8') ?> (<?= htmlspecialchars($code, ENT_QUOTES, 'UTF-8') ?>)
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    
                    <button type="submit" class="btn btn-primary btn-sm px-4 fw-bold"><?= htmlspecialchars(__('install.lang_submit_btn') ?: 'Confirm Language and Continue, Please', ENT_QUOTES, 'UTF-8') ?></button>
                </form>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>
