<?php
// install/index.php - First-time installer wizard for PRD
declare(strict_types=1);

session_start();

$root = dirname(__DIR__); // this project folder only
$configLocal = $root . '/config.local.php';
$lockFile = $root . '/db/INSTALL_LOCK';
$loaderDb = $root . '/db/db.php';

$step = isset($_POST['step']) ? (int) $_POST['step'] : 1;
$error = '';
$message = '';

function install_db_is_empty(PDO $pdo): bool {
    $tables = $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);
    return count($tables) === 0;
}

function install_import_sql(PDO $pdo, string $path): void {
    if (!is_file($path)) {
        throw new RuntimeException("Missing SQL file: {$path}");
    }
    $sql = file_get_contents($path);
    $sql = preg_replace('/\/\*![0-9]{5}.*?\*\//s', '', $sql);
    $sql = preg_replace('/^--.*$/m', '', $sql);
    $sql = preg_replace('/^\/\*M!.*$/m', '', $sql);
    $statements = array_filter(array_map('trim', explode(';', $sql)));

    $pdo->exec('SET FOREIGN_KEY_CHECKS=0');
    try {
        foreach ($statements as $statement) {
            if ($statement === '') {
                continue;
            }
            if (preg_match('/^(SET|USE)\s+/i', $statement)) {
                continue;
            }
            $pdo->exec($statement);
        }
    } finally {
        $pdo->exec('SET FOREIGN_KEY_CHECKS=1');
    }
}

function install_latest_schema_version(string $migrationsDir): int {
    $latest = 0;
    if (is_dir($migrationsDir)) {
        foreach (glob($migrationsDir . '/*.php') as $file) {
            if (preg_match('/(\d+)_/', basename($file), $m)) {
                $latest = max($latest, (int) $m[1]);
            }
        }
    }
    return max(1, $latest);
}

function install_write_config_local(string $path, string $host, string $db, string $user, string $pass): void {
    $hostE = var_export($host, true);
    $dbE   = var_export($db, true);
    $userE = var_export($user, true);
    $passE = var_export($pass, true);

    $content = <<<PHP
<?php
// config.local.php - Generated by installer. Do not commit. This project folder only.
if (!defined('BASE_PATH')) {
    \$doc_root = rtrim(str_replace('\\\\', '/', \$_SERVER['DOCUMENT_ROOT'] ?? ''), '/');
    \$project_root = rtrim(str_replace('\\\\', '/', dirname(__FILE__)), '/');
    \$base_path = str_replace(\$doc_root, '', \$project_root);
    define('BASE_PATH', \$base_path);
}

\$host = {$hostE};
\$db = {$dbE};
\$user = {$userE};
\$pass = {$passE};
\$charset = 'utf8mb4';

\$dsn = "mysql:host=\$host;dbname=\$db;charset=\$charset";
\$options = [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES => false,
];

\$log_dir = __DIR__ . '/logs';
if (!is_dir(\$log_dir)) {
    @mkdir(\$log_dir, 0755, true);
}

try {
    \$pdo = new PDO(\$dsn, \$user, \$pass, \$options);

    // Force MySQL session time zone to UTC (+00:00) to prevent the 1-hour drift
    \$pdo->exec("SET time_zone = '+00:00';");

    if (is_file(__DIR__ . '/db/maintenance_guard.php')) {
        require_once __DIR__ . '/db/maintenance_guard.php';
        if (function_exists('check_maintenance_mode')) {
            check_maintenance_mode(\$pdo);
        }
    }
} catch (PDOException \$e) {
    throw new PDOException('Database Connection Failed: ' . \$e->getMessage(), (int) \$e->getCode());
}

PHP;

    $result = @file_put_contents($path, $content);
    if ($result === false) {
        $last = error_get_last();
        $detail = $last['message'] ?? 'unknown error';
        throw new RuntimeException(
            'Could not write config.local.php (' . $path . '). PHP said: ' . $detail
        );
    }
}

function install_write_loader_db_php(string $path): void {
    $content = <<<'PHP'
<?php
// db/db.php - Generated by installer (loader only). Secrets live in config.local.php.
$projectRoot = dirname(__DIR__);
$configLocal = $projectRoot . '/config.local.php';

if (is_file($configLocal)) {
    require $configLocal;
    return;
}

$script = str_replace('\\', '/', $_SERVER['SCRIPT_NAME'] ?? '');
if (strpos($script, '/install/') !== false || str_ends_with($script, '/install')) {
    return;
}

$base = str_replace('\\', '/', dirname($script));
if (preg_match('#/(user|admin|api|actions|db|partials|includes)(/|$)#', $base)) {
    $base = dirname($base);
}
$base = rtrim($base, '/');
header('Location: ' . $base . '/install/');
exit;

PHP;

    $dir = dirname($path);
    if (!is_dir($dir)) {
        if (!@mkdir($dir, 0755, true) && !is_dir($dir)) {
            throw new RuntimeException('Could not create db/ directory.');
        }
    }
    if (@file_put_contents($path, $content) === false) {
        $last = error_get_last();
        throw new RuntimeException(
            'Could not write db/db.php loader. PHP said: ' . ($last['message'] ?? 'unknown')
        );
    }
}

function install_bootstrap_permissions(PDO $pdo): void {
    $core_permissions = [
        ['manage_settings', 'Manage global site settings, mail drivers, and maintenance mode'],
        ['manage_users', 'Manage user accounts'],
        ['invite_users', 'Create and invite new users'],
        ['manage_tables', 'Manage dynamic database tables and column schema definitions'],
        ['manage_columns', 'Configure table columns'],
        ['edit_records', 'Add, edit, and transcribe records into the system'],
        ['access_data_entry', 'Allows accessing the core data entry workstation and creating records'],
        ['view_public', 'View and search records'],
        ['view_leaderboard', 'Allows viewing community contribution leaderboards'],
        ['manage_feedback', 'Manage feedback'],
        ['submit_feedback', 'Allows submitting public feedback and inquiries'],
        ['manage_volunteers', 'Manage volunteers'],
        ['submit_volunteer', 'Allows submitting volunteer interest and transcription applications'],
        ['moderate_suggestions', 'Approve, reject, or override user edit suggestions'],
        ['manage_moderation', 'Manage and review user correction suggestions and moderation queues'],
        ['moderate_submissions', 'Review and moderate pending user submissions'],
        ['access_profile', 'Allows viewing and managing personal user profile and security settings'],
        ['access_onboarding', 'Allows accessing the first-time user onboarding setup wizard'],
    ];

    $insPerm = $pdo->prepare(
        'INSERT IGNORE INTO permissions (permission_key, description) VALUES (?, ?)'
    );
    foreach ($core_permissions as [$key, $desc]) {
        $insPerm->execute([$key, $desc]);
    }

    $pdo->exec("
        INSERT IGNORE INTO role_permissions (role_id, permission_id)
        SELECT 1, id FROM permissions
    ");

    $pdo->exec("
        INSERT IGNORE INTO role_permissions (role_id, permission_id)
        SELECT 4, id FROM permissions WHERE permission_key = 'view_public'
    ");
}

function install_show_complete_page(): void {
    echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">';
    echo '<title>Setup complete</title>';
    echo '<style>body{font-family:system-ui,sans-serif;max-width:40rem;margin:2rem auto;padding:0 1rem;line-height:1.5}</style></head><body>';
    echo '<h1>Setup complete</h1>';
    echo '<p>This site is already set up. The installer is closed so it cannot be run again by mistake.</p>';
    echo '<p><a href="../user/login.php">Log in</a> · <a href="../index.php">Go to the site</a></p>';
    echo '<p style="font-size:0.9rem;color:#555">You can delete or rename the <code>install</code> folder for extra safety.</p>';
    echo '</body></html>';
    exit;
}

function install_load_pdo_from_config(string $configLocal): PDO {
    if (!is_file($configLocal)) {
        throw new RuntimeException('No config.local.php found.');
    }
    require $configLocal;
    if (!isset($pdo) || !($pdo instanceof PDO)) {
        throw new RuntimeException('Database connection not available.');
    }
    return $pdo;
}

// Probe write access inside this project folder only
$probeOk = false;
$probeError = '';
$probeFile = $root . '/.install_write_probe';
if (@file_put_contents($probeFile, 'ok') !== false) {
    $probeOk = true;
    @unlink($probeFile);
} else {
    $last = error_get_last();
    $probeError = $last['message'] ?? 'write failed';
}

// ---------- Lock / resume ----------
if (is_file($lockFile)) {
    install_show_complete_page();
}

if (is_file($configLocal) && $_SERVER['REQUEST_METHOD'] !== 'POST') {
    try {
        $pdo = install_load_pdo_from_config($configLocal);
        $userCount = (int) $pdo->query('SELECT COUNT(*) FROM users')->fetchColumn();
        if ($userCount > 0) {
            if (!is_dir($root . '/db')) {
                @mkdir($root . '/db', 0755, true);
            }
            if (!is_file($loaderDb)) {
                install_write_loader_db_php($loaderDb);
            }
            install_bootstrap_permissions($pdo);
            file_put_contents($lockFile, 'Installed ' . gmdate('c') . " (lock backfilled)\n");
            install_show_complete_page();
        }
        $_SESSION['install_db_ok'] = true;
        $step = 4;
        $message = 'Database is ready. Create your admin account to finish setup.';
    } catch (Throwable $e) {
        $error = 'Could not use existing config: ' . $e->getMessage();
    }
}

// ---------- POST ----------
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        if ($step === 2) {
            $step = 3;
        } elseif ($step === 3) {
            if (!$probeOk) {
                throw new RuntimeException(
                    'PHP cannot create files in this project folder. '
                    . ($probeError !== '' ? 'Detail: ' . $probeError : '')
                );
            }

            $host = trim($_POST['db_host'] ?? '127.0.0.1');
            $name = trim($_POST['db_name'] ?? '');
            $user = trim($_POST['db_user'] ?? '');
            $pass = $_POST['db_pass'] ?? '';

            if ($name === '' || $user === '') {
                throw new RuntimeException('Database name and database username are required.');
            }

            $dsn = "mysql:host={$host};dbname={$name};charset=utf8mb4";
            $pdo = new PDO($dsn, $user, $pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);

            // Force MySQL session time zone to UTC (+00:00) during installation checks
            $pdo->exec("SET time_zone = '+00:00';");

            if (!install_db_is_empty($pdo)) {
                throw new RuntimeException(
                    'This database is not empty. Use a new empty database (or drop all tables) and try again.'
                );
            }

            install_write_config_local($configLocal, $host, $name, $user, $pass);
            install_write_loader_db_php($loaderDb);

            install_import_sql($pdo, $root . '/db/schema_baseline.sql');
            install_import_sql($pdo, $root . '/db/seed_baseline.sql');
            if (is_file($root . '/db/seed_permissions.sql')) {
                install_import_sql($pdo, $root . '/db/seed_permissions.sql');
            }
            if (is_file($root . '/db/seed_role_permissions.sql')) {
                install_import_sql($pdo, $root . '/db/seed_role_permissions.sql');
            }

            $functions = $root . '/includes/functions.php';
            if (is_file($functions)) {
                require_once $functions;
            }
            $latest = install_latest_schema_version($root . '/db/migrations');
            if (function_exists('set_schema_version')) {
                set_schema_version($pdo, $latest);
            } else {
                $stmt = $pdo->prepare(
                    "INSERT INTO site_settings (setting_key, setting_value) VALUES ('schema_version', ?)
                     ON DUPLICATE KEY UPDATE setting_value = ?"
                );
                $stmt->execute([(string) $latest, (string) $latest]);
            }

            $_SESSION['install_db_ok'] = true;
            $step = 4;
            $message = 'Database connected and schema imported. Create your admin account.';
        } elseif ($step === 4) {
            if (empty($_SESSION['install_db_ok']) || !is_file($configLocal)) {
                throw new RuntimeException('Complete the database step first.');
            }

            $pdo = install_load_pdo_from_config($configLocal);

            $username = trim($_POST['admin_username'] ?? '');
            $email    = trim($_POST['admin_email'] ?? '');
            $password = $_POST['admin_password'] ?? '';
            $confirm  = $_POST['admin_password_confirm'] ?? '';

            if ($username === '' || $email === '' || $password === '') {
                throw new RuntimeException('All admin fields are required.');
            }
            if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
                throw new RuntimeException('Invalid email address.');
            }
            if (strlen($password) < 8) {
                throw new RuntimeException('Password must be at least 8 characters.');
            }
            if ($password !== $confirm) {
                throw new RuntimeException('Passwords do not match.');
            }

            $hash = password_hash($password, PASSWORD_DEFAULT);
            $roleId = 1;

            try {
                // Set is_new_user = 1 so the admin goes through onboarding wizard on first login
                $stmt = $pdo->prepare("
                    INSERT INTO users (username, email, password_hash, role_id, email_verified, is_active, is_new_user)
                    VALUES (?, ?, ?, ?, 1, 1, 1)
                ");
                $stmt->execute([$username, $email, $hash, $roleId]);
            } catch (PDOException $e) {
                $stmt = $pdo->prepare("
                    INSERT INTO users (username, email, password_hash, role_id)
                    VALUES (?, ?, ?, ?)
                ");
                $stmt->execute([$username, $email, $hash, $roleId]);
            }

            $check = $pdo->prepare('SELECT COUNT(*) FROM users WHERE username = ?');
            $check->execute([$username]);
            if ((int) $check->fetchColumn() < 1) {
                throw new RuntimeException('Admin user was not saved. Check the users table structure.');
            }

            install_bootstrap_permissions($pdo);

            if (!is_file($loaderDb)) {
                install_write_loader_db_php($loaderDb);
            }

            if (!is_dir($root . '/db')) {
                @mkdir($root . '/db', 0755, true);
            }
            file_put_contents($lockFile, 'Installed ' . gmdate('c') . "\n");
            unset($_SESSION['install_db_ok']);
            $step = 5;
            $message = 'Installation complete.';
        }
    } catch (Throwable $e) {
        $error = $e->getMessage();
        if ($step === 3 && is_file($configLocal) && empty($_SESSION['install_db_ok'])) {
            @unlink($configLocal);
        }
        if ($step === 4) {
            $step = 4;
            $_SESSION['install_db_ok'] = true;
        }
    }
}

$phpOk = version_compare(PHP_VERSION, '8.0.0', '>=');
$pdoOk = extension_loaded('pdo_mysql');
$logsDir = $root . '/logs';
$logsOk = is_dir($logsDir) ? is_writable($logsDir) : is_writable($root);
$reqsOk = $phpOk && $pdoOk && $logsOk && $probeOk;

$showDbForm = ($step === 3) || ($step < 4 && empty($_SESSION['install_db_ok']) && !is_file($configLocal));

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Install — Parish Records Directory</title>
    <style>
        body { font-family: system-ui, sans-serif; max-width: 40rem; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
        .err { background: #f8d7da; color: #721c24; padding: 0.75rem; border-radius: 4px; }
        .ok { background: #d4edda; color: #155724; padding: 0.75rem; border-radius: 4px; }
        label { display: block; margin-top: 0.75rem; font-weight: 600; }
        input { width: 100%; padding: 0.5rem; box-sizing: border-box; margin-top: 0.25rem; }
        button { margin-top: 1.25rem; padding: 0.6rem 1.2rem; cursor: pointer; }
        ul { padding-left: 1.25rem; }
        .fail { color: #b00020; }
        .pass { color: #0a7a2f; }
        .hint { font-weight: normal; font-size: 0.9rem; color: #555; }
    </style>
</head>
<body>
    <h1>Install</h1>
    <p>First-time setup for <strong>this application folder only</strong>. Use an empty MySQL database.</p>

    <?php if ($error): ?>
        <p class="err"><?php echo htmlspecialchars($error); ?></p>
    <?php endif; ?>
    <?php if ($message && $step !== 5): ?>
        <p class="ok"><?php echo htmlspecialchars($message); ?></p>
    <?php endif; ?>

    <?php if ($step === 5): ?>
        <h2>Done</h2>
        <p class="ok">Installation complete. The installer is now locked.</p>
        <p><a href="../user/login.php">Log in</a> · <a href="../index.php">Go to the site</a></p>

    <?php elseif ($step === 4): ?>
        <h2>Site administrator account</h2>
        <p>This is the login for <strong>this website</strong> (not the database).</p>
        <form method="post">
            <input type="hidden" name="step" value="4">
            <label for="admin_username">Admin username</label>
            <input id="admin_username" name="admin_username" required autocomplete="username">
            <label for="admin_email">Admin email</label>
            <input id="admin_email" name="admin_email" type="email" required autocomplete="email">
            <label for="admin_password">Admin password (min 8 characters)</label>
            <input id="admin_password" name="admin_password" type="password" required autocomplete="new-password">
            <label for="admin_password_confirm">Confirm admin password</label>
            <input id="admin_password_confirm" name="admin_password_confirm" type="password" required autocomplete="new-password">
            <button type="submit">Finish installation</button>
        </form>

    <?php elseif ($showDbForm): ?>
        <h2>Database connection</h2>
        <p class="hint">Use the MySQL details from your <strong>hosting control panel</strong>. This is not the website admin login (that comes next).</p>
        <form method="post">
            <input type="hidden" name="step" value="3">
            <label for="db_host">Database host</label>
            <input id="db_host" name="db_host" value="127.0.0.1" required>
            <label for="db_name">Database name</label>
            <input id="db_name" name="db_name" required>
            <label for="db_user">Database username</label>
            <input id="db_user" name="db_user" required autocomplete="off">
            <label for="db_pass">Database password</label>
            <input id="db_pass" name="db_pass" type="password" autocomplete="new-password">
            <button type="submit">Create tables &amp; continue</button>
        </form>

    <?php else: ?>
        <h2>1. Requirements</h2>
        <ul>
            <li class="<?php echo $phpOk ? 'pass' : 'fail'; ?>">PHP 8.0+ (found <?php echo htmlspecialchars(PHP_VERSION); ?>)</li>
            <li class="<?php echo $pdoOk ? 'pass' : 'fail'; ?>">PDO MySQL extension</li>
            <li class="<?php echo $logsOk ? 'pass' : 'fail'; ?>">Writable logs folder (or project folder)</li>
            <li class="<?php echo $probeOk ? 'pass' : 'fail'; ?>">
                Can create files in this project folder
                <?php if (!$probeOk && $probeError): ?>
                    <br><span class="hint"><?php echo htmlspecialchars($probeError); ?></span>
                <?php endif; ?>
            </li>
        </ul>
        <?php if ($reqsOk): ?>
            <form method="post">
                <input type="hidden" name="step" value="2">
                <button type="submit">Continue</button>
            </form>
        <?php else: ?>
            <p class="err">Fix the failed checks, then reload this page.</p>
        <?php endif; ?>
    <?php endif; ?>
</body>
</html>
