<?php
// install/index.php - First-time installer wizard for PRD
declare(strict_types=1);

session_start();

$root = dirname(__DIR__); // this project folder only
$configLocal = $root . '/config.local.php';
$lockFile = $root . '/db/INSTALL_LOCK';
$loaderDb = $root . '/db/db.php';

$step = isset($_POST['step']) ? (int) $_POST['step'] : 1;
$error = '';
$message = '';

function install_db_is_empty(PDO $pdo): bool {
    $tables = $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);
    return count($tables) === 0;
}

function install_import_sql(PDO $pdo, string $path): void {
    if (!is_file($path)) {
        throw new RuntimeException("Missing SQL file: {$path}");
    }
    $sql = file_get_contents($path);
    $sql = preg_replace('/\/\*![0-9]{5}.*?\*\//s', '', $sql);
    $sql = preg_replace('/^--.*$/m', '', $sql);
    $sql = preg_replace('/^\/\*M!.*$/m', '', $sql);
    $statements = array_filter(array_map('trim', explode(';', $sql)));

    $pdo->exec('SET FOREIGN_KEY_CHECKS=0');
    try {
        foreach ($statements as $statement) {
            if ($statement === '') {
                continue;
            }
            if (preg_match('/^(SET|USE)\s+/i', $statement)) {
                continue;
            }
            $pdo->exec($statement);
        }
    } finally {
        $pdo->exec('SET FOREIGN_KEY_CHECKS=1');
    }
}

function install_latest_schema_version(string $migrationsDir): int {
    $latest = 0;
    if (is_dir($migrationsDir)) {
        foreach (glob($migrationsDir . '/*.php') as $file) {
            if (preg_match('/(\d+)_/', basename($file), $m)) {
                $latest = max($latest, (int) $m[1]);
            }
        }
    }
    return max(1, $latest);
}

function install_write_config_local(string $path, string $host, string $db, string $user, string $pass): void {
    $hostE = var_export($host, true);
    $dbE   = var_export($db, true);
    $userE = var_export($user, true);
    $passE = var_export($pass, true);

    $content = <<<PHP
<?php
// config.local.php - Generated by installer. Do not commit. This project folder only.
if (!defined('BASE_PATH')) {
    \$doc_root = rtrim(str_replace('\\\\', '/', \$_SERVER['DOCUMENT_ROOT'] ?? ''), '/');
    \$project_root = rtrim(str_replace('\\\\', '/', dirname(__FILE__)), '/');
    \$base_path = str_replace(\$doc_root, '', \$project_root);
    define('BASE_PATH', \$base_path);
}

\$host = {$hostE};
\$db = {$dbE};
\$user = {$userE};
\$pass = {$passE};
\$charset = 'utf8mb4';

\$dsn = "mysql:host=\$host;dbname=\$db;charset=\$charset";
\$options = [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES => false,
];

\$log_dir = __DIR__ . '/logs';
if (!is_dir(\$log_dir)) {
    @mkdir(\$log_dir, 0755, true);
}

try {
    \$pdo = new PDO(\$dsn, \$user, \$pass, \$options);

    // Force MySQL session time zone to UTC (+00:00) to prevent the 1-hour drift
    \$pdo->exec("SET time_zone = '+00:00';");

    if (is_file(__DIR__ . '/db/maintenance_guard.php')) {
        require_once __DIR__ . '/db/maintenance_guard.php';
        if (function_exists('check_maintenance_mode')) {
            check_maintenance_mode(\$pdo);
        }
    }
} catch (PDOException \$e) {
    throw new PDOException('Database Connection Failed: ' . \$e->getMessage(), (int) \$e->getCode());
}

PHP;

    $result = @file_put_contents($path, $content);
    if ($result === false) {
        $last = error_get_last();
        $detail = $last['message'] ?? 'unknown error';
        throw new RuntimeException(
            'Could not write config.local.php (' . $path . '). PHP said: ' . $detail
        );
    }
}

function install_write_loader_db_php(string $path): void {
    $content = <<<'PHP'
<?php
// db/db.php - Generated by installer (loader only). Secrets live in config.local.php.
$projectRoot = dirname(__DIR__);
$configLocal = $projectRoot . '/config.local.php';

if (is_file($configLocal)) {
    require $configLocal;
    return;
}

$script = str_replace('\\', '/', $_SERVER['SCRIPT_NAME'] ?? '');
if (strpos($script, '/install/') !== false || str_ends_with($script, '/install')) {
    return;
}

$base = str_replace('\\', '/', dirname($script));
if (preg_match('#/(user|admin|api|actions|db|partials|includes)(/|$)#', $base)) {
    $base = dirname($base);
}
$base = rtrim($base, '/');
header('Location: ' . $base . '/install/');
exit;

PHP;

    $dir = dirname($path);
    if (!is_dir($dir)) {
        if (!@mkdir($dir, 0755, true) && !is_dir($dir)) {
            throw new RuntimeException('Could not create db/ directory.');
        }
    }
    if (@file_put_contents($path, $content) === false) {
        $last = error_get_last();
        throw new RuntimeException(
            'Could not write db/db.php loader. PHP said: ' . ($last['message'] ?? 'unknown')
        );
    }
}

function install_bootstrap_permissions(PDO $pdo): void {
    $registryPath = dirname(__DIR__) . '/db/permissions_registry.php';
    if (!is_file($registryPath)) {
        throw new RuntimeException("Missing permissions registry: {$registryPath}");
    }
    
    $registry = include $registryPath;
    $permissions = $registry['permissions'] ?? [];
    $defaultRoles = $registry['default_roles'] ?? [];

    // 1. Insert all master permissions from registry
    $insPerm = $pdo->prepare(
        'INSERT IGNORE INTO permissions (permission_key, description) VALUES (?, ?)'
    );
    foreach ($permissions as $key => $desc) {
        $insPerm->execute([$key, $desc]);
    }

    // 2. Map default permissions to core roles dynamically from the registry
    foreach ($defaultRoles as $roleName => $permKeys) {
        $stmt = $pdo->prepare("SELECT id FROM roles WHERE role_name = ?");
        $stmt->execute([$roleName]);
        $roleId = $stmt->fetchColumn();

        if ($roleId) {
            foreach ($permKeys as $key) {
                $pStmt = $pdo->prepare("SELECT id FROM permissions WHERE permission_key = ?");
                $pStmt->execute([$key]);
                $permId = $pStmt->fetchColumn();

                if ($permId) {
                    $mapStmt = $pdo->prepare("INSERT IGNORE INTO role_permissions (role_id, permission_id) VALUES (?, ?)");
                    $mapStmt->execute([$roleId, $permId]);
                }
            }
        }
    }
}

function install_show_complete_page(): void {
    echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">';
    echo '<title>' . htmlspecialchars(__('install.complete_title')) . '</title>';
    echo '<style>body{font-family:system-ui,sans-serif;max-width:40rem;margin:2rem auto;padding:0 1rem;line-height:1.5}</style></head><body>';
    echo '<h1>' . htmlspecialchars(__('install.complete_heading')) . '</h1>';
    echo '<p>' . htmlspecialchars(__('install.complete_desc')) . '</p>';
    echo '<p><a href="../user/login.php">' . htmlspecialchars(__('install.login_link')) . '</a> · <a href="../index.php">' . htmlspecialchars(__('install.home_link')) . '</a></p>';
    echo '<p style="font-size:0.9rem;color:#555">' . __('install.delete_folder_hint') . '</p>';
    echo '</body></html>';
    exit;
}

function install_load_pdo_from_config(string $configLocal): PDO {
    if (!is_file($configLocal)) {
        throw new RuntimeException('No config.local.php found.');
    }
    require $configLocal;
    if (!isset($pdo) || !($pdo instanceof PDO)) {
        throw new RuntimeException('Database connection not available.');
    }
    return $pdo;
}

// Probe write access inside this project folder only
$probeOk = false;
$probeError = '';
$probeFile = $root . '/.install_write_probe';
if (@file_put_contents($probeFile, 'ok') !== false) {
    $probeOk = true;
    @unlink($probeFile);
} else {
    $last = error_get_last();
    $probeError = $last['message'] ?? 'write failed';
}

// ---------- Lock / resume ----------
if (is_file($lockFile)) {
    install_show_complete_page();
}

if (is_file($configLocal) && $_SERVER['REQUEST_METHOD'] !== 'POST') {
    try {
        $pdo = install_load_pdo_from_config($configLocal);
        $userCount = (int) $pdo->query('SELECT COUNT(*) FROM users')->fetchColumn();
        if ($userCount > 0) {
            if (!is_dir($root . '/db')) {
                @mkdir($root . '/db', 0755, true);
            }
            if (!is_file($loaderDb)) {
                install_write_loader_db_php($loaderDb);
            }
            install_bootstrap_permissions($pdo);
            file_put_contents($lockFile, 'Installed ' . gmdate('c') . " (lock backfilled)\n");
            install_show_complete_page();
        }
        $_SESSION['install_db_ok'] = true;
        $step = 4;
        $message = __('install.msg_db_ready');
    } catch (Throwable $e) {
        $error = __('install.err_config_load') . ' ' . $e->getMessage();
    }
}

// ---------- POST ----------
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        if ($step === 2) {
            $step = 3;
        } elseif ($step === 3) {
            if (!$probeOk) {
                throw new RuntimeException(
                    __('install.err_write_permission') . ' ' . ($probeError !== '' ? __('install.detail_prefix') . ' ' . $probeError : '')
                );
            }

            $host = trim($_POST['db_host'] ?? '127.0.0.1');
            $name = trim($_POST['db_name'] ?? '');
            $user = trim($_POST['db_user'] ?? '');
            $pass = $_POST['db_pass'] ?? '';

            if ($name === '' || $user === '') {
                throw new RuntimeException(__('install.err_db_required'));
            }

            $dsn = "mysql:host={$host};dbname={$name};charset=utf8mb4";
            $pdo = new PDO($dsn, $user, $pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);

            // Force MySQL session time zone to UTC (+00:00) during installation checks
            $pdo->exec("SET time_zone = '+00:00';");

            if (!install_db_is_empty($pdo)) {
                throw new RuntimeException(__('install.err_db_not_empty'));
            }

            install_write_config_local($configLocal, $host, $name, $user, $pass);
            install_write_loader_db_php($loaderDb);

            install_import_sql($pdo, $root . '/db/schema_baseline.sql');
            install_import_sql($pdo, $root . '/db/seed_baseline.sql');
            if (is_file($root . '/db/seed_permissions.sql')) {
                install_import_sql($pdo, $root . '/db/seed_permissions.sql');
            }
            if (is_file($root . '/db/seed_role_permissions.sql')) {
                install_import_sql($pdo, $root . '/db/seed_role_permissions.sql');
            }

            $functions = $root . '/includes/functions.php';
            if (is_file($functions)) {
                require_once $functions;
            }
            $latest = install_latest_schema_version($root . '/db/migrations');
            if (function_exists('set_schema_version')) {
                set_schema_version($pdo, $latest);
            } else {
                $stmt = $pdo->prepare(
                    "INSERT INTO site_settings (setting_key, setting_value) VALUES ('schema_version', ?)
                     ON DUPLICATE KEY UPDATE setting_value = ?"
                );
                $stmt->execute([(string) $latest, (string) $latest]);
            }

            $_SESSION['install_db_ok'] = true;
            $step = 4;
            $message = __('install.msg_schema_imported');
        } elseif ($step === 4) {
            if (empty($_SESSION['install_db_ok']) || !is_file($configLocal)) {
                throw new RuntimeException(__('install.err_complete_db_first'));
            }

            $pdo = install_load_pdo_from_config($configLocal);

            $username = trim($_POST['admin_username'] ?? '');
            $email    = trim($_POST['admin_email'] ?? '');
            $password = $_POST['admin_password'] ?? '';
            $confirm  = $_POST['admin_password_confirm'] ?? '';

            if ($username === '' || $email === '' || $password === '') {
                throw new RuntimeException(__('install.err_admin_required'));
            }
            if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
                throw new RuntimeException(__('install.err_invalid_email'));
            }
            if (strlen($password) < 8) {
                throw new RuntimeException(__('install.err_password_length'));
            }
            if ($password !== $confirm) {
                throw new RuntimeException(__('install.err_passwords_match'));
            }

            $hash = password_hash($password, PASSWORD_DEFAULT);
            $roleId = 1;

            try {
                $stmt = $pdo->prepare("
                    INSERT INTO users (username, email, password_hash, role_id, email_verified, is_active, is_new_user)
                    VALUES (?, ?, ?, ?, 1, 1, 1)
                ");
                $stmt->execute([$username, $email, $hash, $roleId]);
            } catch (PDOException $e) {
                $stmt = $pdo->prepare("
                    INSERT INTO users (username, email, password_hash, role_id)
                    VALUES (?, ?, ?, ?)
                ");
                $stmt->execute([$username, $email, $hash, $roleId]);
            }

            $check = $pdo->prepare('SELECT COUNT(*) FROM users WHERE username = ?');
            $check->execute([$username]);
            if ((int) $check->fetchColumn() < 1) {
                throw new RuntimeException(__('install.err_admin_save_failed'));
            }

            install_bootstrap_permissions($pdo);

            if (!is_file($loaderDb)) {
                install_write_loader_db_php($loaderDb);
            }

            if (!is_dir($root . '/db')) {
                @mkdir($root . '/db', 0755, true);
            }
            file_put_contents($lockFile, 'Installed ' . gmdate('c') . "\n");
            unset($_SESSION['install_db_ok']);
            $step = 5;
            $message = __('install.msg_installation_complete');
        }
    } catch (Throwable $e) {
        $error = $e->getMessage();
        if ($step === 3 && is_file($configLocal) && empty($_SESSION['install_db_ok'])) {
            @unlink($configLocal);
        }
        if ($step === 4) {
            $step = 4;
            $_SESSION['install_db_ok'] = true;
        }
    }
}

$phpOk = version_compare(PHP_VERSION, '8.0.0', '>=');
$pdoOk = extension_loaded('pdo_mysql');
$logsDir = $root . '/logs';
$logsOk = is_dir($logsDir) ? is_writable($logsDir) : is_writable($root);
$reqsOk = $phpOk && $pdoOk && $logsOk && $probeOk;

$showDbForm = ($step === 3) || ($step < 4 && empty($_SESSION['install_db_ok']) && !is_file($configLocal));

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo htmlspecialchars(__('install.page_title')); ?></title>
    <style>
        body { font-family: system-ui, sans-serif; max-width: 40rem; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
        .err { background: #f8d7da; color: #721c24; padding: 0.75rem; border-radius: 4px; }
        .ok { background: #d4edda; color: #155724; padding: 0.75rem; border-radius: 4px; }
        label { display: block; margin-top: 0.75rem; font-weight: 600; }
        input { width: 100%; padding: 0.5rem; box-sizing: border-box; margin-top: 0.25rem; }
        button { margin-top: 1.25rem; padding: 0.6rem 1.2rem; cursor: pointer; }
        ul { padding-left: 1.25rem; }
        .fail { color: #b00020; }
        .pass { color: #0a7a2f; }
        .hint { font-weight: normal; font-size: 0.9rem; color: #555; }
    </style>
</head>
<body>
    <h1><?php echo htmlspecialchars(__('install.heading')); ?></h1>
    <p><?php echo __('install.subheading'); ?></p>

    <?php if ($error): ?>
        <p class="err"><?php echo htmlspecialchars($error); ?></p>
    <?php endif; ?>
    <?php if ($message && $step !== 5): ?>
        <p class="ok"><?php echo htmlspecialchars($message); ?></p>
    <?php endif; ?>

    <?php if ($step === 5): ?>
        <h2><?php echo htmlspecialchars(__('install.done_heading')); ?></h2>
        <p class="ok"><?php echo htmlspecialchars(__('install.done_message')); ?></p>
        <p><a href="../user/login.php"><?php echo htmlspecialchars(__('install.login_link')); ?></a> · <a href="../index.php"><?php echo htmlspecialchars(__('install.home_link')); ?></a></p>

    <?php elseif ($step === 4): ?>
        <h2><?php echo htmlspecialchars(__('install.admin_heading')); ?></h2>
        <p><?php echo __('install.admin_subheading'); ?></p>
        <form method="post">
            <input type="hidden" name="step" value="4">
            <label for="admin_username"><?php echo htmlspecialchars(__('install.admin_username_label')); ?></label>
            <input id="admin_username" name="admin_username" required autocomplete="username">
            <label for="admin_email"><?php echo htmlspecialchars(__('install.admin_email_label')); ?></label>
            <input id="admin_email" name="admin_email" type="email" required autocomplete="email">
            <label for="admin_password"><?php echo htmlspecialchars(__('install.admin_password_label')); ?></label>
            <input id="admin_password" name="admin_password" type="password" required autocomplete="new-password">
            <label for="admin_password_confirm"><?php echo htmlspecialchars(__('install.admin_confirm_password_label')); ?></label>
            <input id="admin_password_confirm" name="admin_password_confirm" type="password" required autocomplete="new-password">
            <button type="submit"><?php echo htmlspecialchars(__('install.finish_btn')); ?></button>
        </form>

    <?php elseif ($showDbForm): ?>
        <h2><?php echo htmlspecialchars(__('install.db_heading')); ?></h2>
        <p class="hint"><?php echo __('install.db_hint'); ?></p>
        <form method="post">
            <input type="hidden" name="step" value="3">
            <label for="db_host"><?php echo htmlspecialchars(__('install.db_host_label')); ?></label>
            <input id="db_host" name="db_host" value="127.0.0.1" required>
            <label for="db_name"><?php echo htmlspecialchars(__('install.db_name_label')); ?></label>
            <input id="db_name" name="db_name" required>
            <label for="db_user"><?php echo htmlspecialchars(__('install.db_user_label')); ?></label>
            <input id="db_user" name="db_user" required autocomplete="off">
            <label for="db_pass"><?php echo htmlspecialchars(__('install.db_pass_label')); ?></label>
            <input id="db_pass" name="db_pass" type="password" autocomplete="new-password">
            <button type="submit"><?php echo htmlspecialchars(__('install.db_submit_btn')); ?></button>
        </form>

    <?php else: ?>
        <h2><?php echo htmlspecialchars(__('install.req_heading')); ?></h2>
        <ul>
            <li class="<?php echo $phpOk ? 'pass' : 'fail'; ?>"><?php echo htmlspecialchars(sprintf(__('install.req_php'), PHP_VERSION)); ?></li>
            <li class="<?php echo $pdoOk ? 'pass' : 'fail'; ?>"><?php echo htmlspecialchars(__('install.req_pdo')); ?></li>
            <li class="<?php echo $logsOk ? 'pass' : 'fail'; ?>"><?php echo htmlspecialchars(__('install.req_logs')); ?></li>
            <li class="<?php echo $probeOk ? 'pass' : 'fail'; ?>">
                <?php echo htmlspecialchars(__('install.req_probe')); ?>
                <?php if (!$probeOk && $probeError): ?>
                    <br><span class="hint"><?php echo htmlspecialchars($probeError); ?></span>
                <?php endif; ?>
            </li>
        </ul>
        <?php if ($reqsOk): ?>
            <form method="post">
                <input type="hidden" name="step" value="2">
                <button type="submit"><?php echo htmlspecialchars(__('install.continue_btn')); ?></button>
            </form>
        <?php else: ?>
            <p class="err"><?php echo htmlspecialchars(__('install.req_fail_msg')); ?></p>
        <?php endif; ?>
    <?php endif; ?>
</body>
</html>
